# import everything exported in SConstruct

Import('*')

# get a copy of the environment

env=env.Clone()

# this project name and location

PROJECT = "mcu_sdio"
MYDIR = "tests/"+PROJECT

# collect the source files

matches=[]
matches.append(Glob("*.cpp"))

# append the system startup files

matches.append("system/LibraryHacks.cpp")
matches.append("system/f429/Startup.asm")
matches.append("system/f429/System.c")

# here's where the linker script is located

env.Append(LINKFLAGS="-T"+MYDIR+"/system/f429/Linker.ld")

# trigger a build with the correct output name

buildoutdir=MYDIR+"/build/"+mode+"/"

elf=env.Program(PROJECT+".elf",matches)
hex=env.Command(PROJECT+".hex",elf,"arm-none-eabi-objcopy -O ihex "+buildoutdir+PROJECT+".elf "+buildoutdir+PROJECT+".hex")
bin=env.Command(PROJECT+".bin",elf,"arm-none-eabi-objcopy -O binary "+buildoutdir+PROJECT+".elf "+buildoutdir+PROJECT+".bin")
lst=env.Command(PROJECT+".lst",elf,"arm-none-eabi-objdump -h -S "+buildoutdir+PROJECT+".elf > "+buildoutdir+PROJECT+".lst")
size=env.Command(PROJECT+".size",elf,"arm-none-eabi-size --format=berkeley "+buildoutdir+PROJECT+".elf | tee "+buildoutdir+PROJECT+".size")

# return the hex file 

Return("hex")
